package org.trading.db;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public final class DatabaseInitializer {
    private static DatabaseInitializer instance;

    private DatabaseInitializer() {
    }

    public static synchronized DatabaseInitializer getInstance() {
        if (instance == null) {
            instance = new DatabaseInitializer();
        }
        return instance;
    }

    public void initialize() {
        try (Connection connection = DatabaseConnection.getInstance().getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS stocks (
                        symbol VARCHAR(20) PRIMARY KEY,
                        price DOUBLE PRECISION NOT NULL,
                        company_name VARCHAR(100) NOT NULL,
                        dividend_yield DOUBLE PRECISION NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS cryptos (
                        symbol VARCHAR(20) PRIMARY KEY,
                        price DOUBLE PRECISION NOT NULL,
                        blockchain VARCHAR(100) NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS investors (
                        username VARCHAR(100) PRIMARY KEY,
                        balance DOUBLE PRECISION NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS portfolio_items (
                        username VARCHAR(100) NOT NULL,
                        asset_symbol VARCHAR(20) NOT NULL,
                        quantity INTEGER NOT NULL,
                        average_buy_price DOUBLE PRECISION NOT NULL,
                        PRIMARY KEY (username, asset_symbol),
                        FOREIGN KEY (username) REFERENCES investors(username) ON DELETE CASCADE
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS transactions (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(100),
                        type VARCHAR(10) NOT NULL,
                        asset_symbol VARCHAR(20) NOT NULL,
                        quantity INTEGER NOT NULL,
                        price_per_unit DOUBLE PRECISION NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        FOREIGN KEY (username) REFERENCES investors(username) ON DELETE SET NULL
                    )
                    """);
            statement.execute("""
                    CREATE OR REPLACE FUNCTION total_portfolio_quantity(p_username VARCHAR)
                    RETURNS INTEGER AS $$
                    DECLARE
                        total_quantity INTEGER;
                    BEGIN
                        SELECT COALESCE(SUM(quantity), 0)::INTEGER
                        INTO total_quantity
                        FROM portfolio_items
                        WHERE username = p_username;

                        RETURN total_quantity;
                    END;
                    $$ LANGUAGE plpgsql
                    """);
        } catch (SQLException e) {
            throw new IllegalStateException("Nu s-a putut initializa schema bazei de date.", e);
        }
    }
}
